### PR TITLE
Update service principal role to AzureML Compute Operator for improved security

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Checklist:

- [ ] I have followed the [contribution guidelines](CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] I have [signed the commits](https://github.com/recommenders-team/recommenders/wiki/How-to-sign-commits), e.g. `git commit -s -m "your commit message"`. 
- [ ] This PR is being made to `staging branch` AND NOT TO `main branch`.

### CODE REVIEW

**Review by anargyri — APPROVED** [review]

**Comment by miguelgfierro** [comment]
Issue https://github.com/recommenders-team/recommenders/issues/2170

**Comment by miguelgfierro** [comment]
We added the reader role to the SP and tried again to run the tests: https://github.com/recommenders-team/recommenders/actions/runs/10996608019

**Comment by anargyri** [comment]
Some documentation on the roles https://learn.microsoft.com/en-us/azure/machine-learning/how-to-assign-roles?view=azureml-api-2&tabs=team-lead#default-roles

**Comment by miguelgfierro** [comment]
Everything worked. Merging.

**Pull request merged**
