### PR TITLE
Issue with SliRec and DKN OOM

### LINKED ISSUE #2063: [BUG] OOM in nightly SliRec and DKN
### Description

SLiRec:
```
2024-02-19T18:34:57.2954866Z     @pytest.mark.gpu
2024-02-19T18:34:57.2955209Z     @pytest.mark.notebooks
2024-02-19T18:34:57.2955584Z     @pytest.mark.parametrize(
2024-02-19T18:34:57.2956266Z         "yaml_file, data_path, epochs, batch_size, expected_values, seed",
2024-02-19T18:34:57.2956825Z         [
2024-02-19T18:34:57.2957104Z             (
2024-02-19T18:34:57.2957503Z                 "recommenders/models/deeprec/config/sli_rec.yaml",
2024-02-19T18:34:57.2958128Z                 os.path.join("tests", "resources", "deeprec", "slirec"),
2024-02-19T18:34:57.2958630Z                 10,
2024-02-19T18:34:57.2958948Z                 400,
2024-02-19T18:34:57.2959620Z                 ***"auc": 0.7183***,  # Don't do logloss check as SLi-Rec uses ranking loss, not a point-wise loss
2024-02-19T18:34:57.2960251Z                 42,
2024-02-19T18:34:57.2960549Z             )
2024-02-19T18:34:57.2960841Z         ],
2024-02-19T18:34:57.2961116Z     )
2024-02-19T18:34:57.2961430Z     def test_slirec_quickstart_functional(
2024-02-19T18:34:57.2961851Z         notebooks,
2024-02-19T18:34:57.2962168Z         output_notebook,
2024-02-19T18:34:57.2962505Z         kernel_name,
2024-02-19T18:34:57.2962827Z         yaml_file,
2024-02-19T18:34:57.2963138Z         data_path,
2024-02-19T18:34:57.2963434Z         epochs,
2024-02-19T18:34:57.2963891Z         batch_size,
2024-02-19T18:34:57.2964215Z         expected_values,
2024-02-19T18:34:57.2964557Z         seed,
2024-02-19T18:34:57.2964842Z     ):
2024-02-19T18:34:57.2965198Z         notebook_path = notebooks["slirec_quickstart"]
2024-02-19T18:34:57.2965660Z     
2024-02-19T18:34:57.2965951Z         params = ***
2024-02-19T18:34:57.2966294Z             "yaml_file": yaml_file,
2024-02-19T18:34:57.2966694Z             "data_path": data_path,
2024-02-19T18:34:57.2967077Z             "EPOCHS": epochs,
2024-02-19T18:34:57.2967455Z             "BATCH_SIZE": batch_size,
2024-02-19T18:34:57.2967858Z             "RANDOM_SEED": seed,
2024-02-19T18:34:57.2968237Z         ***
2024-02-19T18:34:57.2968533Z >       execute_notebook(
2024-02-19T18:34:57.2969074Z             notebook_path, output_notebook, kernel_name=kernel_name, parameters=params
2024-02-19T18:34:57.2969651Z         )
...
...
2024-02-19T18:34:57.3146322Z E           Node: 'gradients/sequential/sli_rec/attention_fcn/attention_fcn/att_fcn/nn_part/Tensordot/MatMul_grad/MatMul'
2024-02-19T18:34:57.3147524Z E           OOM when allocating tensor with shape[100000,160] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2024-02-19T18:34:57.3148737Z E           	 [[***node gradients/sequential/sli_rec/attention_fcn/attention_fcn/att_fcn/nn_part/Tensordot/MatMul_grad/MatMul***]]
2024-02-19T18:34:57.3150345Z E           Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
...
...
2024-02-19T18:34:57.5143539Z 2024-02-19 18:33:33.543531: I external/local_tsl/tsl/framework/bfc_allocator.cc:1103] 1 Chunks of size 19795968 totalling 18.88MiB
2024-02-19T18:34:57.5144130Z 2024-02-19 18:33:33.543537: I external/local_tsl/tsl/framework/bfc_allocator.cc:1103] 1 Chunks of size 32000000 totalling 30.52MiB
2024-02-19T18:34:57.5144750Z 2024-02-19 18:33:33.543543: I external/local_tsl/tsl/framework/bfc_allocator.cc:1103] 1 Chunks of size 76880128 totalling 73.32MiB
2024-02-19T18:34:57.5145349Z 2024-02-19 18:33:33.543549: I external/local_tsl/tsl/framework/bfc_allocator.cc:1107] Sum Total of in-use chunks: 490.36MiB
2024-02-19T18:34:57.5146324Z 2024-02-19 18:33:33.543555: I external/local_tsl/tsl/framework/bfc_allocator.cc:1109] Total bytes in pool: 735707136 memory_limit_: 735707136 available bytes: 0 curr_region_allocation_bytes_: 1471414272
2024-02-19T18:34:57.5146770Z 2024-02-19 18:33:33.543565: I external/local_tsl/tsl/framework/bfc_allocator.cc:1114] Stats: 
2024-02-19T18:34:57.5146926Z Limit:                       735707136
2024-02-19T18:34:57.5147068Z InUse:                       514176000
2024-02-19T18:34:57.5147210Z MaxInUse:                    670024448
2024-02-19T18:34:57.5147351Z NumAllocs:                      339864
2024-02-19T18:34:57.5147496Z MaxAllocSize:                 87159808
2024-02-19T18:34:57.5147640Z Reserved:                            0
2024-02-19T18:34:57.5147787Z PeakReserved:                        0
2024-02-19T18:34:57.5147937Z LargestFreeBlock:                    0
2024-02-19T18:34:57.5147944Z 
2024-02-19T18:34:57.5148849Z 2024-02-19 18:33:33.543609: W external/local_tsl/tsl/framework/bfc_allocator.cc:497] *****************************************_***_*******_____**_***____***______*********___**********x
2024-02-19T18:34:57.5150187Z 2024-02-19 18:33:33.543631: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at matmul_op_impl.h:921 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[100000,160] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
```

DKN:
```
2024-02-19T18:34:57.2599869Z     @pytest.mark.gpu
2024-02-19T18:34:57.2600449Z     @pytest.mark.notebooks
2024-02-19T18:34:57.2601381Z     def test_dkn_quickstart_functional(notebooks, output_notebook, kernel_name):
2024-02-19T18:34:57.2602467Z         notebook_path = notebooks["dkn_quickstart"]
2024-02-19T18:34:57.2603235Z >       execute_notebook(
2024-02-19T18:34:57.2603812Z             notebook_path,
2024-02-19T18:34:57.2604398Z             output_notebook,
2024-02-19T18:34:57.2605021Z             kernel_name=kernel_name,
2024-02-19T18:34:57.2606077Z             parameters=dict(EPOCHS=5, BATCH_SIZE=500),
2024-02-19T18:34:57.2606847Z         )
...
...
2024-02-19T18:34:57.2824248Z E             (0) NOT_FOUND: No algorithm worked!  Error messages:
2024-02-19T18:34:57.2825665Z E             Profiling failure on CUDNN engine eng11***: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.
2024-02-19T18:34:57.2826837Z E             Profiling failure on CUDNN engine eng0***: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.
2024-02-19T18:34:57.2827773Z E           	 [[***node DKN/attention_net/kcnn/conv-maxpool-3_1/relu***]]
2024-02-19T18:34:57.2828293Z E           	 [[pred/_15]]
2024-02-19T18:34:57.2828736Z E             (1) NOT_FOUND: No algorithm worked!  Error messages:
2024-02-19T18:34:57.2829605Z E             Profiling failure on CUDNN engine eng11***: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.
2024-02-19T18:34:57.2830719Z E             Profiling failure on CUDNN engine eng0***: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.
2024-02-19T18:34:57.2831642Z E           	 [[***node DKN/attention_net/kcnn/conv-maxpool-3_1/relu***]]

```

### How do we replicate the issue?

See https://github.com/recommenders-team/recommenders/actions/runs/7963399372/job/21738878728

### Other Comments
FYI @SimonYansenZhao

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

Fix #2063

I run both tests in a local V100 and they pass. In the nightly tests I get: https://github.com/recommenders-team/recommenders/actions/workflows/azureml-gpu-nightly.yml?query=branch%3Amiguel%2Fnightly_oom 

The DKN test is already with 5 epochs and BS=200. I don´t know if both tests are conflicting because TF takes the whole memory of the GPU by default. 

This shouldn't happen because in the [BaseModel class](https://github.com/recommenders-team/recommenders/blob/main/recommenders/models/deeprec/models/base_model.py#L69) we have `gpu_options = tf.compat.v1.GPUOptions(allow_growth=True)`. However, when I run the code in local, I see TF getting all the memory.

### Checklist:

- [ ] I have followed the [contribution guidelines](CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] I have [signed the commits](https://github.com/recommenders-team/recommenders/wiki/How-to-sign-commits), e.g. `git commit -s -m "your commit message"`. 
- [ ] This PR is being made to `staging branch` AND NOT TO `main branch`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
If I comment all tests except SLiRec, then it works, and it is quick:
```
INFO:submit_groupwise_azureml_pytest.py:Executing tests now...
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-8.1.1, pluggy-1.4.0
rootdir: /mnt/azureml/cr/j/a2150f1522ab4d47941d5730dcfc5eb8/exe/wd
configfile: pyproject.toml
plugins: mock-3.14.0, hypothesis-6.99.13, typeguard-4.2.1, cov-5.0.0, anyio-4.3.0
collected 2 items

tests/unit/examples/test_notebooks_gpu.py .                              [ 50%]
tests/functional/examples/test_notebooks_gpu.py 

============================== slowest durations ===============================
343.83s call     tests/functional/examples/test_notebooks_gpu.py::test_slirec_quickstart_functional[recommenders/models/deeprec/config/sli_rec.yaml-tests/resources/deeprec/slirec-5-300-expected_values0-42]
1.36s call     tests/unit/examples/test_notebooks_gpu.py::test_gpu_vm

(4 durations < 0.005s hidden.  Use -vv to show these durations.)
================== 2 passed, 12 warnings in 348.30s (0:05:48) ==================
INFO:submit_groupwise_azureml_pytest.py:Test execution completed!
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 5.421173095703125 seconds
```
See https://github.com/recommenders-team/recommenders/actions/runs/8422556385/job/23062115526

**Comment by miguelgfierro** [comment]
@SimonYansenZhao feel free to continue in this branch https://github.com/recommenders-team/recommenders/pull/2076 

The problem I'm seeing is that each test for some reason keeps the memory so the next test get an OOM. I tried `tf.keras.backend.clear_session()`  but it didn't work. Also, in [BaseModel class](https://github.com/recommenders-team/recommenders/blob/main/recommenders/models/deeprec/models/base_model.py#L69) we have `gpu_options = tf.compat.v1.GPUOptions(allow_growth=True)`. However, when I run the code in local, I see TF getting all the memory.

**Comment by SimonYansenZhao** [comment]
> @SimonYansenZhao feel free to continue in this branch #2076
> 
> The problem I'm seeing is that each test for some reason keeps the memory so the next test get an OOM. I tried `tf.keras.backend.clear_session()` but it didn't work. Also, in [BaseModel class](https://github.com/recommenders-team/recommenders/blob/main/recommenders/models/deeprec/models/base_model.py#L69) we have `gpu_options = tf.compat.v1.GPUOptions(allow_growth=True)`. However, when I run the code in local, I see TF getting all the memory.

Yeah, I ran each tests individually today, and all passed.  I'll try to run the three tests together.

**Comment by SimonYansenZhao** [comment]
@miguelgfierro all tests including nightly builds passed after #2077 was merged.  Not sure what's going on with the OOM issue.   But I think we can merge staging into main now.

**Comment by miguelgfierro** [comment]
@SimonYansenZhao I´m freaking out.

**Comment by miguelgfierro** [comment]
Let me run again the nightlys

**Comment by miguelgfierro** [comment]
All nightly works. Closing this

**Pull request closed without merging**
