### PR TITLE
Limit scipy <1.11.0 until #1954 is fixed

### LINKED ISSUE #1954: [BUG] SAR needs to be modified due to a breaking change in scipy
### Description

With scipy 1.10.1, the item similarity matrix is a dense matrix
```
print(type(model.item_similarity))
print(type(model.user_affinity))
print(type(model.item_similarity) == np.ndarray)
print(type(model.item_similarity) == scipy.sparse._csr.csr_matrix)
print(model.item_similarity.shape)
print(model.item_similarity)

<class 'numpy.ndarray'>
<class 'scipy.sparse._csr.csr_matrix'>
True
False
(1646, 1646)
[[1.         0.10650888 0.03076923 ... 0.         0.         0.        ]
 [0.10650888 1.         0.15104167 ... 0.         0.00729927 0.00729927]
 [0.03076923 0.15104167 1.         ... 0.         0.         0.01190476]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.00729927 0.         ... 0.         1.         0.        ]
 [0.         0.00729927 0.01190476 ... 0.         0.         1.        ]]
```

but with scipy 1.11.1 the item similarity matrix is sparse
```
print(type(model.item_similarity))
print(type(model.user_affinity))
type(model.item_similarity) == np.ndarray
type(model.item_similarity) == scipy.sparse._csr.csr_matrix
print(model.item_similarity.shape)
<class 'numpy.ndarray'>
<class 'scipy.sparse._csr.csr_matrix'>
()
```

### In which platform does it happen?

Related to https://github.com/microsoft/recommenders/issues/1951

### Other Comments
We found that the issue was that during a division in Jaccard, scipy change the type. We talked to the authors of scipy and they told us that they did a breaking change in 1.11.0 https://github.com/scipy/scipy/issues/18796#issuecomment-1619125257

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

On Aug 18, a new version of scipy was released and broke our tests again. We need to fix #1954, otherwise, all new versions of scipy won't work. 

This PR restrict the dep to <1.11.0 until we fix that issue

### Related Issues

See https://github.com/recommenders-team/recommenders/actions/runs/5907706378/job/16026070536#step:16:3608

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
@loomlike this one is the solution to the other PRs that are failing, until this one is not merged, we can´t do much

**Comment by loomlike** [comment]
Does #1954 require a big changes or can it be done quickly?

**Comment by miguelgfierro** [comment]
> Does https://github.com/recommenders-team/recommenders/issues/1954 require a big changes or can it be done quickly?

It might be quick

**Review by loomlike — APPROVED** [review]

**Comment by loomlike** [comment]
I created #1980 so that we can track to revert this later.

**Pull request merged**
