### PR TITLE
Changing Function Name to reflect new Tensorflow interface.

### PR DESCRIPTION
**Pull request by siyerp**
Changed a function call name to reflect a more recent version of tensorflow.

### Description
I changed .reset_states() to .reset_state().  
I was getting an error along the lines of "'Mean' object has no attribute 'reset_states'." It seems that in a newer version of tensorflow, the function has been renamed to .reset_state.

### References
[](https://github.com/tensorflow/tensorflow/issues/50359)

### Checklist:

- [ x] I have followed the [contribution guidelines](CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ x] I have [signed the commits](https://github.com/recommenders-team/recommenders/wiki/How-to-sign-commits), e.g. `git commit -s -m "your commit message"`. 
- [ x] This PR is being made to `staging branch` AND NOT TO `main branch`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
@siyerp thanks for this. 

Can you share what TF version are you using?

FYI @daviddavo

**Comment by daviddavo** [comment]
It doesn't appear in the changelog, but they changed it in 2.5.

- [2.5 has reset_state](https://www.tensorflow.org/versions/r2.5/api_docs/python/tf/keras/metrics/Mean#reset_state)
- [2.4 has reset_states](https://www.tensorflow.org/versions/r2.4/api_docs/python/tf/keras/metrics/Mean#reset_states)
- [Relevant TF Commit](https://github.com/tensorflow/tensorflow/commit/acbc065f8eb2ed05c7ab5c42b5c5bd6abdd2f91f), which is available since [v2.5.0-rc0](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0-rc0)

I ran the tests on my machine and they work

**Comment by siyerp** [comment]
@miguelgfierro I'm using Tensorflow 2.16, but even in the example notebook it says it's using Tensorflow 2.8, and according to to @daviddavo 's comment, even that should have had this issue.

**Review by miguelgfierro — APPROVED** [review]

**Comment by miguelgfierro** [comment]
Merging this.

Please @siyerp notice that https://github.com/recommenders-team/recommenders/issues/2111 is in the works. If you want to collaborate on this effort, please let me know

**Comment by hao-joey-zhang** [comment]
Had the same issue, try tensorflow==2.12.0

**Pull request merged**
