### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Checklist:

- [ ] I have followed the [contribution guidelines](CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] I have [signed the commits](https://github.com/recommenders-team/recommenders/wiki/How-to-sign-commits), e.g. `git commit -s -m "your commit message"`. 
- [ ] This PR is being made to `staging branch` AND NOT TO `main branch`.

### CODE REVIEW

**Comment by SimonYansenZhao** [comment]
I would suggest the 'slack|join' badge/button be placed under the recommenders logo or be bigger so that people can notice there is a slack channel they can join.  @miguelgfierro

**Review by anargyri — APPROVED** [review]

**Comment by anargyri** [comment]
The slack badge is a bit misaligned when I open the front page on my PC.
image

**Comment by miguelgfierro** [comment]
@anargyri the one with slack at the level of Recommenders or this one:
image

**Comment by anargyri** [comment]
Even better now
image

**Comment by anargyri** [comment]
Another thing: we don't really need the title "Recommenders" if we have the logo that says the same thing, do we?

**Comment by miguelgfierro** [comment]
image


I like it more without Recommenders repeated. Looks nice!

What do you think @SimonYansenZhao?

**Pull request merged**
